Fix webpack build error (#109)
## Description

- Catches up some dependencies with `npm install`.
- Updates the CI and deployment `Node.js` version to accommodate one of
those updated dependencies.
- Removes an extraneous line from a test.

## Motivation and Context

App build was failing to complete with the following error.

```
Failed to compile.

HookWebpackError: _webpack.WebpackError is not a constructor
    at makeWebpackError (/app/node_modules/next/dist/compiled/webpack/bundle5.js:29:315765)
    at /app/node_modules/next/dist/compiled/webpack/bundle5.js:29:106471
    at eval (eval at create (/app/node_modules/next/dist/compiled/webpack/bundle5.js:14:9224), <anonymous>:58:1)
-- inner error --
TypeError: _webpack.WebpackError is not a constructor
    at buildError (/app/node_modules/next/dist/build/webpack/plugins/minify-webpack-plugin/src/index.js:24:16)
    at /app/node_modules/next/dist/build/webpack/plugins/minify-webpack-plugin/src/index.js:137:57
    at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:157:20)
caused by plugins in Compilation.hooks.processAssets
TypeError: _webpack.WebpackError is not a constructor
    at buildError (/app/node_modules/next/dist/build/webpack/plugins/minify-webpack-plugin/src/index.js:24:16)
    at /app/node_modules/next/dist/build/webpack/plugins/minify-webpack-plugin/src/index.js:137:57
    at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:157:20)


> Build failed because of webpack errors
```

This had made it out to the dev instance deployments. I created a new
ticket (PP 3955) to update CI to perform a built, which should help us
catch this kind of issue before a PR is merged.


## How Has This Been Tested?

- Tested building in local environment with `npm run build` and `npm run
dev` in my development environment.
- All tests pass locally.
- [CI
checks](https://github.com/ThePalaceProject/web-patron/actions/runs/23457537955)
pass.

## Checklist:

- N/A - I have updated the documentation accordingly.
- [x] All new and existing tests passed.